# Try writing a GitHub Action with Python code inline to check links.

name: "Check for private links"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  check-links:
    name: "Check for private links"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.after }}

      - name: Checkout more
        run: |
          git checkout ${{ github.base_ref }}
          git checkout ${{ github.head_ref }}

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: "Install the linter"
        run: |
          python -m pip install 'edx-repo-tools[private_link_linter] @ git+https://github.com/openedx/repo-tools.git@nedbat/private-link-linter'

      - name: "Run the code"
        env:
          TITLE: ${{ github.event.pull_request.title }}
          DESCRIPTION: ${{ github.event.pull_request.body }}
        run: |
          git rev-list --header ${{ github.base_ref }}..${{ github.head_ref}} | private_link_linter "$TITLE" "$DESCRIPTION"
