# Try writing a GitHub Action with Python code inline to check links.

name: "Check for private links"

on:
  pull_request:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  check-links:
    name: "Check for private links"
    runs-on: ubuntu-latest

    steps:
      - name: "Dump context"
        uses: crazy-max/ghaction-dump-context@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.after }}

      - name: Checkout more
        run: |
          git checkout ${{ github.base_ref }}
          git checkout ${{ github.head_ref }}

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: "Install requirements"
        run: |
          python -m pip install requests

      - name: "Create code to run"
        run: |
          cat > check-links.py <<EOF
          # This is a Python file
          for i in range(10):
              print(i)
          EOF

      - name: "Run the code"
        run: |
          python check-links.py

      - name: "Show the description"
        env:
          DESCRIPTION: ${{ github.event.pull_request.body }}
        run: |
          echo "$DESCRIPTION"

      - name: "Show the commits"
        run: |
          git log --format="%B" ${{ github.base_ref }}..${{ github.head_ref}}
